const nameItem = {
  point: [
    {
      id: 1,
      title: "Місто",
      point1: "Львів",
      point2: "Київ",
      point3: "Харків",
      point4: "Херсон",
      point5: "Одеса",
      point6: "Дніпро",
      point7: "Ужгород",
    },
    {
      id: 2,
      title: "Стать",
      point1: "Самець",
      point2: "Самка",
      point3: "Інше",
      point4: "",
      point5: "",
      point6: "",
      point7: "",
    },
    {
      id: 3,
      title: "Вік",
      point1: "0 - 5 місяців",
      point2: "6 - 12 місяців",
      point3: "1 - 3 роки",
      point4: "3 - 6 років",
      point5: "6 і більше років",
      point6: "",
      point7: "",
    },
    {
      id: 4,
      title: "Стерелізація",
      point1: "так",
      point2: "ні",
      point3: "",
      point4: "",
      point5: "",
      point6: "",
      point7: "",
    },
    {
      id: 5,
      title: "Наявність щеплень",
      point1: "так",
      point2: "ні",
      point3: "",
      point4: "",
      point5: "",
      point6: "",
      point7: "",
    },
  ],
};
export default nameItem;
